# Generated by Django 4.1 on 2023-07-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quora", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answers",
            new_name="Answer",
        ),
    ]
